export const FONT_FAMILY = 'Cambria, Cochin, Georgia, Times, "Times New Roman", serif';
export const MENU_ITEM_COLOR = "#aaa";
export const MENU_ITEM_SELECTED_COLOR = "#eee";
export const DRUM_SIZE_PX = 250;
export const DRUM_SIZE_XS_PX = 210;
export const PATTERN_SIZE_PX = 40;
export const PATTERN_SIZE_XS_PX = 30;
export const PATTERN_MARGIN_PX = 5;
export const PATTERN_MARGIN_XS_PX = 3;
